// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Messages.proto

package org.galatea.starter.entrypoint.messagecontracts;

@javax.annotation.Generated("protoc")
public final class Messages {
  private Messages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TradeAgreementMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:fuse_java_starter.TradeAgreementMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 id = 1;</code>
     */
    long getId();

    /**
     * <code>string instrument = 2;</code>
     */
    java.lang.String getInstrument();
    /**
     * <code>string instrument = 2;</code>
     */
    com.google.protobuf.ByteString
        getInstrumentBytes();

    /**
     * <code>string internal_party = 3;</code>
     */
    java.lang.String getInternalParty();
    /**
     * <code>string internal_party = 3;</code>
     */
    com.google.protobuf.ByteString
        getInternalPartyBytes();

    /**
     * <code>string external_party = 4;</code>
     */
    java.lang.String getExternalParty();
    /**
     * <code>string external_party = 4;</code>
     */
    com.google.protobuf.ByteString
        getExternalPartyBytes();

    /**
     * <code>string buy_sell = 5;</code>
     */
    java.lang.String getBuySell();
    /**
     * <code>string buy_sell = 5;</code>
     */
    com.google.protobuf.ByteString
        getBuySellBytes();

    /**
     * <code>double qty = 6;</code>
     */
    double getQty();
  }
  /**
   * <pre>
   * defines the message format for trade agreements 
   * </pre>
   *
   * Protobuf type {@code fuse_java_starter.TradeAgreementMessage}
   */
  public  static final class TradeAgreementMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:fuse_java_starter.TradeAgreementMessage)
      TradeAgreementMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TradeAgreementMessage.newBuilder() to construct.
    private TradeAgreementMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TradeAgreementMessage() {
      id_ = 0L;
      instrument_ = "";
      internalParty_ = "";
      externalParty_ = "";
      buySell_ = "";
      qty_ = 0D;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TradeAgreementMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              id_ = input.readInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              instrument_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              internalParty_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              externalParty_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              buySell_ = s;
              break;
            }
            case 49: {

              qty_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.galatea.starter.entrypoint.messagecontracts.Messages.internal_static_fuse_java_starter_TradeAgreementMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.galatea.starter.entrypoint.messagecontracts.Messages.internal_static_fuse_java_starter_TradeAgreementMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.galatea.starter.entrypoint.messagecontracts.Messages.TradeAgreementMessage.class, org.galatea.starter.entrypoint.messagecontracts.Messages.TradeAgreementMessage.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int INSTRUMENT_FIELD_NUMBER = 2;
    private volatile java.lang.Object instrument_;
    /**
     * <code>string instrument = 2;</code>
     */
    public java.lang.String getInstrument() {
      java.lang.Object ref = instrument_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        instrument_ = s;
        return s;
      }
    }
    /**
     * <code>string instrument = 2;</code>
     */
    public com.google.protobuf.ByteString
        getInstrumentBytes() {
      java.lang.Object ref = instrument_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        instrument_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INTERNAL_PARTY_FIELD_NUMBER = 3;
    private volatile java.lang.Object internalParty_;
    /**
     * <code>string internal_party = 3;</code>
     */
    public java.lang.String getInternalParty() {
      java.lang.Object ref = internalParty_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        internalParty_ = s;
        return s;
      }
    }
    /**
     * <code>string internal_party = 3;</code>
     */
    public com.google.protobuf.ByteString
        getInternalPartyBytes() {
      java.lang.Object ref = internalParty_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        internalParty_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXTERNAL_PARTY_FIELD_NUMBER = 4;
    private volatile java.lang.Object externalParty_;
    /**
     * <code>string external_party = 4;</code>
     */
    public java.lang.String getExternalParty() {
      java.lang.Object ref = externalParty_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        externalParty_ = s;
        return s;
      }
    }
    /**
     * <code>string external_party = 4;</code>
     */
    public com.google.protobuf.ByteString
        getExternalPartyBytes() {
      java.lang.Object ref = externalParty_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        externalParty_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BUY_SELL_FIELD_NUMBER = 5;
    private volatile java.lang.Object buySell_;
    /**
     * <code>string buy_sell = 5;</code>
     */
    public java.lang.String getBuySell() {
      java.lang.Object ref = buySell_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        buySell_ = s;
        return s;
      }
    }
    /**
     * <code>string buy_sell = 5;</code>
     */
    public com.google.protobuf.ByteString
        getBuySellBytes() {
      java.lang.Object ref = buySell_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        buySell_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int QTY_FIELD_NUMBER = 6;
    private double qty_;
    /**
     * <code>double qty = 6;</code>
     */
    public double getQty() {
      return qty_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (!getInstrumentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, instrument_);
      }
      if (!getInternalPartyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, internalParty_);
      }
      if (!getExternalPartyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, externalParty_);
      }
      if (!getBuySellBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, buySell_);
      }
      if (qty_ != 0D) {
        output.writeDouble(6, qty_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (!getInstrumentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, instrument_);
      }
      if (!getInternalPartyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, internalParty_);
      }
      if (!getExternalPartyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, externalParty_);
      }
      if (!getBuySellBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, buySell_);
      }
      if (qty_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(6, qty_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.galatea.starter.entrypoint.messagecontracts.Messages.TradeAgreementMessage)) {
        return super.equals(obj);
      }
      org.galatea.starter.entrypoint.messagecontracts.Messages.TradeAgreementMessage other = (org.galatea.starter.entrypoint.messagecontracts.Messages.TradeAgreementMessage) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && getInstrument()
          .equals(other.getInstrument());
      result = result && getInternalParty()
          .equals(other.getInternalParty());
      result = result && getExternalParty()
          .equals(other.getExternalParty());
      result = result && getBuySell()
          .equals(other.getBuySell());
      result = result && (
          java.lang.Double.doubleToLongBits(getQty())
          == java.lang.Double.doubleToLongBits(
              other.getQty()));
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + INSTRUMENT_FIELD_NUMBER;
      hash = (53 * hash) + getInstrument().hashCode();
      hash = (37 * hash) + INTERNAL_PARTY_FIELD_NUMBER;
      hash = (53 * hash) + getInternalParty().hashCode();
      hash = (37 * hash) + EXTERNAL_PARTY_FIELD_NUMBER;
      hash = (53 * hash) + getExternalParty().hashCode();
      hash = (37 * hash) + BUY_SELL_FIELD_NUMBER;
      hash = (53 * hash) + getBuySell().hashCode();
      hash = (37 * hash) + QTY_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getQty()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.galatea.starter.entrypoint.messagecontracts.Messages.TradeAgreementMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.galatea.starter.entrypoint.messagecontracts.Messages.TradeAgreementMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.galatea.starter.entrypoint.messagecontracts.Messages.TradeAgreementMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.galatea.starter.entrypoint.messagecontracts.Messages.TradeAgreementMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.galatea.starter.entrypoint.messagecontracts.Messages.TradeAgreementMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.galatea.starter.entrypoint.messagecontracts.Messages.TradeAgreementMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.galatea.starter.entrypoint.messagecontracts.Messages.TradeAgreementMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.galatea.starter.entrypoint.messagecontracts.Messages.TradeAgreementMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.galatea.starter.entrypoint.messagecontracts.Messages.TradeAgreementMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.galatea.starter.entrypoint.messagecontracts.Messages.TradeAgreementMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.galatea.starter.entrypoint.messagecontracts.Messages.TradeAgreementMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.galatea.starter.entrypoint.messagecontracts.Messages.TradeAgreementMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.galatea.starter.entrypoint.messagecontracts.Messages.TradeAgreementMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * defines the message format for trade agreements 
     * </pre>
     *
     * Protobuf type {@code fuse_java_starter.TradeAgreementMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:fuse_java_starter.TradeAgreementMessage)
        org.galatea.starter.entrypoint.messagecontracts.Messages.TradeAgreementMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.galatea.starter.entrypoint.messagecontracts.Messages.internal_static_fuse_java_starter_TradeAgreementMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.galatea.starter.entrypoint.messagecontracts.Messages.internal_static_fuse_java_starter_TradeAgreementMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.galatea.starter.entrypoint.messagecontracts.Messages.TradeAgreementMessage.class, org.galatea.starter.entrypoint.messagecontracts.Messages.TradeAgreementMessage.Builder.class);
      }

      // Construct using org.galatea.starter.entrypoint.messagecontracts.Messages.TradeAgreementMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0L;

        instrument_ = "";

        internalParty_ = "";

        externalParty_ = "";

        buySell_ = "";

        qty_ = 0D;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.galatea.starter.entrypoint.messagecontracts.Messages.internal_static_fuse_java_starter_TradeAgreementMessage_descriptor;
      }

      public org.galatea.starter.entrypoint.messagecontracts.Messages.TradeAgreementMessage getDefaultInstanceForType() {
        return org.galatea.starter.entrypoint.messagecontracts.Messages.TradeAgreementMessage.getDefaultInstance();
      }

      public org.galatea.starter.entrypoint.messagecontracts.Messages.TradeAgreementMessage build() {
        org.galatea.starter.entrypoint.messagecontracts.Messages.TradeAgreementMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.galatea.starter.entrypoint.messagecontracts.Messages.TradeAgreementMessage buildPartial() {
        org.galatea.starter.entrypoint.messagecontracts.Messages.TradeAgreementMessage result = new org.galatea.starter.entrypoint.messagecontracts.Messages.TradeAgreementMessage(this);
        result.id_ = id_;
        result.instrument_ = instrument_;
        result.internalParty_ = internalParty_;
        result.externalParty_ = externalParty_;
        result.buySell_ = buySell_;
        result.qty_ = qty_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.galatea.starter.entrypoint.messagecontracts.Messages.TradeAgreementMessage) {
          return mergeFrom((org.galatea.starter.entrypoint.messagecontracts.Messages.TradeAgreementMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.galatea.starter.entrypoint.messagecontracts.Messages.TradeAgreementMessage other) {
        if (other == org.galatea.starter.entrypoint.messagecontracts.Messages.TradeAgreementMessage.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (!other.getInstrument().isEmpty()) {
          instrument_ = other.instrument_;
          onChanged();
        }
        if (!other.getInternalParty().isEmpty()) {
          internalParty_ = other.internalParty_;
          onChanged();
        }
        if (!other.getExternalParty().isEmpty()) {
          externalParty_ = other.externalParty_;
          onChanged();
        }
        if (!other.getBuySell().isEmpty()) {
          buySell_ = other.buySell_;
          onChanged();
        }
        if (other.getQty() != 0D) {
          setQty(other.getQty());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.galatea.starter.entrypoint.messagecontracts.Messages.TradeAgreementMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.galatea.starter.entrypoint.messagecontracts.Messages.TradeAgreementMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long id_ ;
      /**
       * <code>int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>int64 id = 1;</code>
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object instrument_ = "";
      /**
       * <code>string instrument = 2;</code>
       */
      public java.lang.String getInstrument() {
        java.lang.Object ref = instrument_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          instrument_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string instrument = 2;</code>
       */
      public com.google.protobuf.ByteString
          getInstrumentBytes() {
        java.lang.Object ref = instrument_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          instrument_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string instrument = 2;</code>
       */
      public Builder setInstrument(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        instrument_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string instrument = 2;</code>
       */
      public Builder clearInstrument() {
        
        instrument_ = getDefaultInstance().getInstrument();
        onChanged();
        return this;
      }
      /**
       * <code>string instrument = 2;</code>
       */
      public Builder setInstrumentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        instrument_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object internalParty_ = "";
      /**
       * <code>string internal_party = 3;</code>
       */
      public java.lang.String getInternalParty() {
        java.lang.Object ref = internalParty_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          internalParty_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string internal_party = 3;</code>
       */
      public com.google.protobuf.ByteString
          getInternalPartyBytes() {
        java.lang.Object ref = internalParty_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          internalParty_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string internal_party = 3;</code>
       */
      public Builder setInternalParty(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        internalParty_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string internal_party = 3;</code>
       */
      public Builder clearInternalParty() {
        
        internalParty_ = getDefaultInstance().getInternalParty();
        onChanged();
        return this;
      }
      /**
       * <code>string internal_party = 3;</code>
       */
      public Builder setInternalPartyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        internalParty_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object externalParty_ = "";
      /**
       * <code>string external_party = 4;</code>
       */
      public java.lang.String getExternalParty() {
        java.lang.Object ref = externalParty_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          externalParty_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string external_party = 4;</code>
       */
      public com.google.protobuf.ByteString
          getExternalPartyBytes() {
        java.lang.Object ref = externalParty_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          externalParty_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string external_party = 4;</code>
       */
      public Builder setExternalParty(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        externalParty_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string external_party = 4;</code>
       */
      public Builder clearExternalParty() {
        
        externalParty_ = getDefaultInstance().getExternalParty();
        onChanged();
        return this;
      }
      /**
       * <code>string external_party = 4;</code>
       */
      public Builder setExternalPartyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        externalParty_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object buySell_ = "";
      /**
       * <code>string buy_sell = 5;</code>
       */
      public java.lang.String getBuySell() {
        java.lang.Object ref = buySell_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          buySell_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string buy_sell = 5;</code>
       */
      public com.google.protobuf.ByteString
          getBuySellBytes() {
        java.lang.Object ref = buySell_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          buySell_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string buy_sell = 5;</code>
       */
      public Builder setBuySell(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        buySell_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string buy_sell = 5;</code>
       */
      public Builder clearBuySell() {
        
        buySell_ = getDefaultInstance().getBuySell();
        onChanged();
        return this;
      }
      /**
       * <code>string buy_sell = 5;</code>
       */
      public Builder setBuySellBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        buySell_ = value;
        onChanged();
        return this;
      }

      private double qty_ ;
      /**
       * <code>double qty = 6;</code>
       */
      public double getQty() {
        return qty_;
      }
      /**
       * <code>double qty = 6;</code>
       */
      public Builder setQty(double value) {
        
        qty_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double qty = 6;</code>
       */
      public Builder clearQty() {
        
        qty_ = 0D;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:fuse_java_starter.TradeAgreementMessage)
    }

    // @@protoc_insertion_point(class_scope:fuse_java_starter.TradeAgreementMessage)
    private static final org.galatea.starter.entrypoint.messagecontracts.Messages.TradeAgreementMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.galatea.starter.entrypoint.messagecontracts.Messages.TradeAgreementMessage();
    }

    public static org.galatea.starter.entrypoint.messagecontracts.Messages.TradeAgreementMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TradeAgreementMessage>
        PARSER = new com.google.protobuf.AbstractParser<TradeAgreementMessage>() {
      public TradeAgreementMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TradeAgreementMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TradeAgreementMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TradeAgreementMessage> getParserForType() {
      return PARSER;
    }

    public org.galatea.starter.entrypoint.messagecontracts.Messages.TradeAgreementMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SettlementMissionMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:fuse_java_starter.SettlementMissionMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 id = 1;</code>
     */
    long getId();

    /**
     * <code>string instrument = 2;</code>
     */
    java.lang.String getInstrument();
    /**
     * <code>string instrument = 2;</code>
     */
    com.google.protobuf.ByteString
        getInstrumentBytes();

    /**
     * <code>string external_party = 3;</code>
     */
    java.lang.String getExternalParty();
    /**
     * <code>string external_party = 3;</code>
     */
    com.google.protobuf.ByteString
        getExternalPartyBytes();

    /**
     * <code>string depot = 4;</code>
     */
    java.lang.String getDepot();
    /**
     * <code>string depot = 4;</code>
     */
    com.google.protobuf.ByteString
        getDepotBytes();

    /**
     * <code>string direction = 5;</code>
     */
    java.lang.String getDirection();
    /**
     * <code>string direction = 5;</code>
     */
    com.google.protobuf.ByteString
        getDirectionBytes();

    /**
     * <code>double qty = 6;</code>
     */
    double getQty();
  }
  /**
   * <pre>
   * defines the message format for settlement missions 
   * </pre>
   *
   * Protobuf type {@code fuse_java_starter.SettlementMissionMessage}
   */
  public  static final class SettlementMissionMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:fuse_java_starter.SettlementMissionMessage)
      SettlementMissionMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SettlementMissionMessage.newBuilder() to construct.
    private SettlementMissionMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SettlementMissionMessage() {
      id_ = 0L;
      instrument_ = "";
      externalParty_ = "";
      depot_ = "";
      direction_ = "";
      qty_ = 0D;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SettlementMissionMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              id_ = input.readInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              instrument_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              externalParty_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              depot_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              direction_ = s;
              break;
            }
            case 49: {

              qty_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.galatea.starter.entrypoint.messagecontracts.Messages.internal_static_fuse_java_starter_SettlementMissionMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.galatea.starter.entrypoint.messagecontracts.Messages.internal_static_fuse_java_starter_SettlementMissionMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.galatea.starter.entrypoint.messagecontracts.Messages.SettlementMissionMessage.class, org.galatea.starter.entrypoint.messagecontracts.Messages.SettlementMissionMessage.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int INSTRUMENT_FIELD_NUMBER = 2;
    private volatile java.lang.Object instrument_;
    /**
     * <code>string instrument = 2;</code>
     */
    public java.lang.String getInstrument() {
      java.lang.Object ref = instrument_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        instrument_ = s;
        return s;
      }
    }
    /**
     * <code>string instrument = 2;</code>
     */
    public com.google.protobuf.ByteString
        getInstrumentBytes() {
      java.lang.Object ref = instrument_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        instrument_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXTERNAL_PARTY_FIELD_NUMBER = 3;
    private volatile java.lang.Object externalParty_;
    /**
     * <code>string external_party = 3;</code>
     */
    public java.lang.String getExternalParty() {
      java.lang.Object ref = externalParty_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        externalParty_ = s;
        return s;
      }
    }
    /**
     * <code>string external_party = 3;</code>
     */
    public com.google.protobuf.ByteString
        getExternalPartyBytes() {
      java.lang.Object ref = externalParty_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        externalParty_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEPOT_FIELD_NUMBER = 4;
    private volatile java.lang.Object depot_;
    /**
     * <code>string depot = 4;</code>
     */
    public java.lang.String getDepot() {
      java.lang.Object ref = depot_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        depot_ = s;
        return s;
      }
    }
    /**
     * <code>string depot = 4;</code>
     */
    public com.google.protobuf.ByteString
        getDepotBytes() {
      java.lang.Object ref = depot_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        depot_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DIRECTION_FIELD_NUMBER = 5;
    private volatile java.lang.Object direction_;
    /**
     * <code>string direction = 5;</code>
     */
    public java.lang.String getDirection() {
      java.lang.Object ref = direction_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        direction_ = s;
        return s;
      }
    }
    /**
     * <code>string direction = 5;</code>
     */
    public com.google.protobuf.ByteString
        getDirectionBytes() {
      java.lang.Object ref = direction_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        direction_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int QTY_FIELD_NUMBER = 6;
    private double qty_;
    /**
     * <code>double qty = 6;</code>
     */
    public double getQty() {
      return qty_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (!getInstrumentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, instrument_);
      }
      if (!getExternalPartyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, externalParty_);
      }
      if (!getDepotBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, depot_);
      }
      if (!getDirectionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, direction_);
      }
      if (qty_ != 0D) {
        output.writeDouble(6, qty_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (!getInstrumentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, instrument_);
      }
      if (!getExternalPartyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, externalParty_);
      }
      if (!getDepotBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, depot_);
      }
      if (!getDirectionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, direction_);
      }
      if (qty_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(6, qty_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.galatea.starter.entrypoint.messagecontracts.Messages.SettlementMissionMessage)) {
        return super.equals(obj);
      }
      org.galatea.starter.entrypoint.messagecontracts.Messages.SettlementMissionMessage other = (org.galatea.starter.entrypoint.messagecontracts.Messages.SettlementMissionMessage) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && getInstrument()
          .equals(other.getInstrument());
      result = result && getExternalParty()
          .equals(other.getExternalParty());
      result = result && getDepot()
          .equals(other.getDepot());
      result = result && getDirection()
          .equals(other.getDirection());
      result = result && (
          java.lang.Double.doubleToLongBits(getQty())
          == java.lang.Double.doubleToLongBits(
              other.getQty()));
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + INSTRUMENT_FIELD_NUMBER;
      hash = (53 * hash) + getInstrument().hashCode();
      hash = (37 * hash) + EXTERNAL_PARTY_FIELD_NUMBER;
      hash = (53 * hash) + getExternalParty().hashCode();
      hash = (37 * hash) + DEPOT_FIELD_NUMBER;
      hash = (53 * hash) + getDepot().hashCode();
      hash = (37 * hash) + DIRECTION_FIELD_NUMBER;
      hash = (53 * hash) + getDirection().hashCode();
      hash = (37 * hash) + QTY_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getQty()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.galatea.starter.entrypoint.messagecontracts.Messages.SettlementMissionMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.galatea.starter.entrypoint.messagecontracts.Messages.SettlementMissionMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.galatea.starter.entrypoint.messagecontracts.Messages.SettlementMissionMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.galatea.starter.entrypoint.messagecontracts.Messages.SettlementMissionMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.galatea.starter.entrypoint.messagecontracts.Messages.SettlementMissionMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.galatea.starter.entrypoint.messagecontracts.Messages.SettlementMissionMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.galatea.starter.entrypoint.messagecontracts.Messages.SettlementMissionMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.galatea.starter.entrypoint.messagecontracts.Messages.SettlementMissionMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.galatea.starter.entrypoint.messagecontracts.Messages.SettlementMissionMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.galatea.starter.entrypoint.messagecontracts.Messages.SettlementMissionMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.galatea.starter.entrypoint.messagecontracts.Messages.SettlementMissionMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.galatea.starter.entrypoint.messagecontracts.Messages.SettlementMissionMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.galatea.starter.entrypoint.messagecontracts.Messages.SettlementMissionMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * defines the message format for settlement missions 
     * </pre>
     *
     * Protobuf type {@code fuse_java_starter.SettlementMissionMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:fuse_java_starter.SettlementMissionMessage)
        org.galatea.starter.entrypoint.messagecontracts.Messages.SettlementMissionMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.galatea.starter.entrypoint.messagecontracts.Messages.internal_static_fuse_java_starter_SettlementMissionMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.galatea.starter.entrypoint.messagecontracts.Messages.internal_static_fuse_java_starter_SettlementMissionMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.galatea.starter.entrypoint.messagecontracts.Messages.SettlementMissionMessage.class, org.galatea.starter.entrypoint.messagecontracts.Messages.SettlementMissionMessage.Builder.class);
      }

      // Construct using org.galatea.starter.entrypoint.messagecontracts.Messages.SettlementMissionMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0L;

        instrument_ = "";

        externalParty_ = "";

        depot_ = "";

        direction_ = "";

        qty_ = 0D;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.galatea.starter.entrypoint.messagecontracts.Messages.internal_static_fuse_java_starter_SettlementMissionMessage_descriptor;
      }

      public org.galatea.starter.entrypoint.messagecontracts.Messages.SettlementMissionMessage getDefaultInstanceForType() {
        return org.galatea.starter.entrypoint.messagecontracts.Messages.SettlementMissionMessage.getDefaultInstance();
      }

      public org.galatea.starter.entrypoint.messagecontracts.Messages.SettlementMissionMessage build() {
        org.galatea.starter.entrypoint.messagecontracts.Messages.SettlementMissionMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.galatea.starter.entrypoint.messagecontracts.Messages.SettlementMissionMessage buildPartial() {
        org.galatea.starter.entrypoint.messagecontracts.Messages.SettlementMissionMessage result = new org.galatea.starter.entrypoint.messagecontracts.Messages.SettlementMissionMessage(this);
        result.id_ = id_;
        result.instrument_ = instrument_;
        result.externalParty_ = externalParty_;
        result.depot_ = depot_;
        result.direction_ = direction_;
        result.qty_ = qty_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.galatea.starter.entrypoint.messagecontracts.Messages.SettlementMissionMessage) {
          return mergeFrom((org.galatea.starter.entrypoint.messagecontracts.Messages.SettlementMissionMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.galatea.starter.entrypoint.messagecontracts.Messages.SettlementMissionMessage other) {
        if (other == org.galatea.starter.entrypoint.messagecontracts.Messages.SettlementMissionMessage.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (!other.getInstrument().isEmpty()) {
          instrument_ = other.instrument_;
          onChanged();
        }
        if (!other.getExternalParty().isEmpty()) {
          externalParty_ = other.externalParty_;
          onChanged();
        }
        if (!other.getDepot().isEmpty()) {
          depot_ = other.depot_;
          onChanged();
        }
        if (!other.getDirection().isEmpty()) {
          direction_ = other.direction_;
          onChanged();
        }
        if (other.getQty() != 0D) {
          setQty(other.getQty());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.galatea.starter.entrypoint.messagecontracts.Messages.SettlementMissionMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.galatea.starter.entrypoint.messagecontracts.Messages.SettlementMissionMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long id_ ;
      /**
       * <code>int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>int64 id = 1;</code>
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object instrument_ = "";
      /**
       * <code>string instrument = 2;</code>
       */
      public java.lang.String getInstrument() {
        java.lang.Object ref = instrument_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          instrument_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string instrument = 2;</code>
       */
      public com.google.protobuf.ByteString
          getInstrumentBytes() {
        java.lang.Object ref = instrument_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          instrument_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string instrument = 2;</code>
       */
      public Builder setInstrument(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        instrument_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string instrument = 2;</code>
       */
      public Builder clearInstrument() {
        
        instrument_ = getDefaultInstance().getInstrument();
        onChanged();
        return this;
      }
      /**
       * <code>string instrument = 2;</code>
       */
      public Builder setInstrumentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        instrument_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object externalParty_ = "";
      /**
       * <code>string external_party = 3;</code>
       */
      public java.lang.String getExternalParty() {
        java.lang.Object ref = externalParty_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          externalParty_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string external_party = 3;</code>
       */
      public com.google.protobuf.ByteString
          getExternalPartyBytes() {
        java.lang.Object ref = externalParty_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          externalParty_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string external_party = 3;</code>
       */
      public Builder setExternalParty(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        externalParty_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string external_party = 3;</code>
       */
      public Builder clearExternalParty() {
        
        externalParty_ = getDefaultInstance().getExternalParty();
        onChanged();
        return this;
      }
      /**
       * <code>string external_party = 3;</code>
       */
      public Builder setExternalPartyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        externalParty_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object depot_ = "";
      /**
       * <code>string depot = 4;</code>
       */
      public java.lang.String getDepot() {
        java.lang.Object ref = depot_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          depot_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string depot = 4;</code>
       */
      public com.google.protobuf.ByteString
          getDepotBytes() {
        java.lang.Object ref = depot_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          depot_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string depot = 4;</code>
       */
      public Builder setDepot(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        depot_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string depot = 4;</code>
       */
      public Builder clearDepot() {
        
        depot_ = getDefaultInstance().getDepot();
        onChanged();
        return this;
      }
      /**
       * <code>string depot = 4;</code>
       */
      public Builder setDepotBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        depot_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object direction_ = "";
      /**
       * <code>string direction = 5;</code>
       */
      public java.lang.String getDirection() {
        java.lang.Object ref = direction_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          direction_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string direction = 5;</code>
       */
      public com.google.protobuf.ByteString
          getDirectionBytes() {
        java.lang.Object ref = direction_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          direction_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string direction = 5;</code>
       */
      public Builder setDirection(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        direction_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string direction = 5;</code>
       */
      public Builder clearDirection() {
        
        direction_ = getDefaultInstance().getDirection();
        onChanged();
        return this;
      }
      /**
       * <code>string direction = 5;</code>
       */
      public Builder setDirectionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        direction_ = value;
        onChanged();
        return this;
      }

      private double qty_ ;
      /**
       * <code>double qty = 6;</code>
       */
      public double getQty() {
        return qty_;
      }
      /**
       * <code>double qty = 6;</code>
       */
      public Builder setQty(double value) {
        
        qty_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double qty = 6;</code>
       */
      public Builder clearQty() {
        
        qty_ = 0D;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:fuse_java_starter.SettlementMissionMessage)
    }

    // @@protoc_insertion_point(class_scope:fuse_java_starter.SettlementMissionMessage)
    private static final org.galatea.starter.entrypoint.messagecontracts.Messages.SettlementMissionMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.galatea.starter.entrypoint.messagecontracts.Messages.SettlementMissionMessage();
    }

    public static org.galatea.starter.entrypoint.messagecontracts.Messages.SettlementMissionMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SettlementMissionMessage>
        PARSER = new com.google.protobuf.AbstractParser<SettlementMissionMessage>() {
      public SettlementMissionMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SettlementMissionMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SettlementMissionMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SettlementMissionMessage> getParserForType() {
      return PARSER;
    }

    public org.galatea.starter.entrypoint.messagecontracts.Messages.SettlementMissionMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fuse_java_starter_TradeAgreementMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_fuse_java_starter_TradeAgreementMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fuse_java_starter_SettlementMissionMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_fuse_java_starter_SettlementMissionMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016Messages.proto\022\021fuse_java_starter\"\206\001\n\025" +
      "TradeAgreementMessage\022\n\n\002id\030\001 \001(\003\022\022\n\nins" +
      "trument\030\002 \001(\t\022\026\n\016internal_party\030\003 \001(\t\022\026\n" +
      "\016external_party\030\004 \001(\t\022\020\n\010buy_sell\030\005 \001(\t\022" +
      "\013\n\003qty\030\006 \001(\001\"\201\001\n\030SettlementMissionMessag" +
      "e\022\n\n\002id\030\001 \001(\003\022\022\n\ninstrument\030\002 \001(\t\022\026\n\016ext" +
      "ernal_party\030\003 \001(\t\022\r\n\005depot\030\004 \001(\t\022\021\n\tdire" +
      "ction\030\005 \001(\t\022\013\n\003qty\030\006 \001(\001B;\n/org.galatea." +
      "starter.entrypoint.messagecontractsB\010Mes" +
      "sagesb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_fuse_java_starter_TradeAgreementMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_fuse_java_starter_TradeAgreementMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_fuse_java_starter_TradeAgreementMessage_descriptor,
        new java.lang.String[] { "Id", "Instrument", "InternalParty", "ExternalParty", "BuySell", "Qty", });
    internal_static_fuse_java_starter_SettlementMissionMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_fuse_java_starter_SettlementMissionMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_fuse_java_starter_SettlementMissionMessage_descriptor,
        new java.lang.String[] { "Id", "Instrument", "ExternalParty", "Depot", "Direction", "Qty", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
