name: PR Build

on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    uses: galatea-associates/fuse-starter-java/.github/workflows/build.yml
  integration-tests:
    uses: galatea-associates/fuse-starter-java/.github/workflows/run-integration-tests.yml